config/routes.rb
Wwhs::Application.routes.draw do

	scope "admin" do
		get "/", :controller => :admin, :action => :index
		match 'tour/:id/setup' => 'tours#setup'		
		match 'tour/:id/print' => 'tours#print'
		resources :tours
		resources :images
		resources :users
		resources :pages
		match 'uchronists/print' => 'uchronists#print'
	  resources :uchronists
	  resources :uchronias
	  resources :user_biographies
	  match 'sync' => 'user_biographies#sync'
		match 'allbios' => 'user_biographies#all'
		
	end

	resources :pages, :only => ['show']
	
	match 'splash' => 'splash#index'	
	match 'splash/register' => 'splash#register'
	match 'splash/unregister' => 'splash#unregister'
	
	match 'j' => redirect("/")
	
	root to: 'jmpress#index'
	

  

  
end

app/models/uchronist.rb
# encoding: utf-8

class Uchronist < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  attr_accessible :description, :image_id, :media_embed, :name, :hidden, :uchronia_ids, :sex
	belongs_to :image
	has_and_belongs_to_many :uchronias

	SEX_OPTIONS = ['weiblich', 'männlich', 'keine Angabe']
	validates :sex, :inclusion => SEX_OPTIONS

	def next_uchronist
		u = self.class.first(:conditions => ["name > ? and hidden = false", name], :order => "name asc")
	  unless u
	  	u = self.class.first(:order => "name asc")
	  end
	  return u
	end

end

app/controllers/uchronists_controller.rb
class UchronistsController < ApplicationController

  before_filter :authenticate, except: [:show]

  layout :set_layout
  
  def set_layout
  	if action_name == "print"
  		return 'print' 
  	else
		return 'admin'   
	end
  end

  # GET /uchronists/print
  def print
    @uchronists = Uchronist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @uchronists }
    end
  end

  # GET /uchronists
  # GET /uchronists.json
  def index
    @uchronists = Uchronist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @uchronists }
    end
  end

  # GET /uchronists/1
  # GET /uchronists/1.json
  def show
    @uchronist = Uchronist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @uchronist }
    end
  end

  # GET /uchronists/new
  # GET /uchronists/new.json
  def new
    @uchronist = Uchronist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @uchronist }
    end
  end

  # GET /uchronists/1/edit
  def edit
    @uchronist = Uchronist.find(params[:id])
  end

  # POST /uchronists
  # POST /uchronists.json
  def create
    @uchronist = Uchronist.new(params[:uchronist])

    respond_to do |format|
      if @uchronist.save
        format.html { redirect_to @uchronist, notice: 'Uchronist was successfully created.' }
        format.json { render json: @uchronist, status: :created, location: @uchronist }
      else
        format.html { render action: "new" }
        format.json { render json: @uchronist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /uchronists/1
  # PUT /uchronists/1.json
  def update
    @uchronist = Uchronist.find(params[:id])

    respond_to do |format|
      if @uchronist.update_attributes(params[:uchronist])
        format.html { redirect_to @uchronist, notice: 'Uchronist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @uchronist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uchronists/1
  # DELETE /uchronists/1.json
  def destroy
    @uchronist = Uchronist.find(params[:id])
    @uchronist.destroy

    respond_to do |format|
      format.html { redirect_to uchronists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/uchronists_helper.rb
module UchronistsHelper
end

app/views/uchronists/_form.html.erb
<%= form_for(@uchronist) do |f| %>
  <% if @uchronist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@uchronist.errors.count, "error") %> prohibited this uchronist from being saved:</h2>

      <ul>
      <% @uchronist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_id %><br />
    <%= f.select :image_id, Image.order("title").collect {|i| [i.title, i.id]}.insert(0, ["-", nil]) %>
  </div>
  <div class="field">
    <%= f.label :media_embed %><br />
    <%= f.text_area :media_embed %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
  <%= f.label "Geschlecht" %>
    <%= f.select :sex, Uchronist::SEX_OPTIONS %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

	<p>  
  <% Uchronia.all.each do |uchronia| %>
  	<%= check_box_tag "uchronist[uchronia_ids][]", uchronia.id, @uchronist.uchronias.include?(uchronia) %>
  	<%= uchronia.title %>  
  <% end %>
  </p>
  
  <div class="field">
    <%= f.label :hidden %><br />
    <%= f.check_box :hidden %>
  </div>

  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/uchronists/_show_public.html.erb
<div class="main">

	<h1>Uchronist<% if uchronist.sex == 'weiblich' %>in<% end %> <%= uchronist.name %></h1>
	
	<div class="row">
		<div class="col-2">
			<% if uchronist.image %>
				<%= image_tag uchronist.image.image.url(:medium) %>
			<% end %> 
			
			<% if uchronist.media_embed %>
				<%= uchronist.media_embed.html_safe %>
			<% end %>
			
		</div>
		
		<div class="col-2">
			<%= uchronist.description.html_safe %>
	
			<p>
				<b>Untersucht die Uchronien</b> <% uchronist.uchronias.each do |u| %>
					<%= link_to u.title, "#/" + u.slug %>
				<% end %>
			</p>
	
		</div>
	</div>

</div>

<div class="row col-1">
	<nav>
		<%= link_to "Weiter", "#/" + uchronist.next_uchronist.slug %> oder <%= link_to "zurück zum Start", "#/start" %>
	</nav>
</div>

app/views/uchronists/edit.html.erb
<h1>Editing uchronist</h1>

<%= render 'form' %>

<%= link_to 'Show', @uchronist %> |
<%= link_to 'Back', uchronists_path %>

app/views/uchronists/index.html.erb
<h1>Listing uchronists</h1>

<table class="table">
  <tr>
    <th>Image</th>
    <th>Media embed</th>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @uchronists.each do |uchronist| %>
  <tr>
    <td>
    	<% if uchronist.image %>
    		<%= image_tag(uchronist.image.image.url(:thumb)) %>
    	<% end %>
    </td>
    <td><%= uchronist.media_embed %></td>
    <td><%= uchronist.name %></td>
    <td><%= uchronist.description %></td>
    <td><%= link_to 'Show', uchronist %></td>
    <td><%= link_to 'Edit', edit_uchronist_path(uchronist) %></td>
    <td><%= link_to 'Destroy', uchronist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Uchronist', new_uchronist_path %>

app/views/uchronists/new.html.erb
<h1>New uchronist</h1>

<%= render 'form' %>

<%= link_to 'Back', uchronists_path %>

app/views/uchronists/print.html.erb
<div class="uchronists">
	<% @uchronists.each do |uchronist| %>
	
		<div class="page-a4">
	
			<h1>Uchronist<% if uchronist.sex == 'weiblich' %>in<% end %><br>
			<%= uchronist.name %></h1>
			
			<div>
				<% if uchronist.image %>
					<%= image_tag uchronist.image.image.url(:original) %>
				<% end %> 
				
				<% if uchronist.media_embed %>
					<%= uchronist.media_embed.html_safe %>
				<% end %>
				
			</div>
			
			<div>
				<%= uchronist.description.html_safe %>
			
			</div>
		
		</div>
	
	<% end %>
</div>

app/views/uchronists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image:</b>
  <%= @uchronist.image_id %>
</p>

<p>
  <b>Media embed:</b>
  <%= @uchronist.media_embed %>
</p>

<p>
  <b>Name:</b>
  <%= @uchronist.name %>
</p>

<p>
  <b>Description:</b>
  <%= @uchronist.description %>
</p>

<p>
  <b>Description:</b>
  <%= @uchronist.description %>
</p>

<p>
  Untersucht die Uchronien: <% @uchronist.uchronias.each do |uchronia| %>
  	<%= uchronia.title %>,   
  <% end %>
</p>

<%= link_to 'Edit', edit_uchronist_path(@uchronist) %> |
<%= link_to 'Back', uchronists_path %>