config/routes.rb
Wwhs::Application.routes.draw do

	scope "admin" do
		get "/", :controller => :admin, :action => :index
		match 'tour/:id/setup' => 'tours#setup'		
		match 'tour/:id/print' => 'tours#print'
		resources :tours
		resources :images
		resources :users
		resources :pages
		match 'uchronists/print' => 'uchronists#print'
	  resources :uchronists
	  resources :uchronias
	  resources :user_biographies
	  match 'sync' => 'user_biographies#sync'
		match 'allbios' => 'user_biographies#all'
		
	end

	resources :pages, :only => ['show']
	
	match 'splash' => 'splash#index'	
	match 'splash/register' => 'splash#register'
	match 'splash/unregister' => 'splash#unregister'
	
	match 'j' => redirect("/")
	
	root to: 'jmpress#index'
	

  

  
end

app/models/uchronia.rb
class Uchronia < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  attr_accessible :description, :image_id, :media_embed, :pod, :title, :hidden, :slug, :show_bio, :uchronist_ids
	belongs_to :image
	has_and_belongs_to_many :uchronists

	def next_uchronia
		sorted = Uchronia.all.sort_by { |u| u.slug.to_i }
		sorted.each_with_index do |u, index| 
			if u.id == self.id 
				return sorted[index+1] unless index+1 >= sorted.count
			end
		end
		return sorted[0]
	end

end

app/controllers/uchronias_controller.rb
class UchroniasController < ApplicationController

  before_filter :authenticate, except: [:show]
  layout 'admin' 

  # GET /uchronias
  # GET /uchronias.json
  def index
    @uchronias = Uchronia.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @uchronias }
    end
  end

  # GET /uchronias/1
  # GET /uchronias/1.json
  def show
    @uchronia = Uchronia.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @uchronia }
    end
  end

  # GET /uchronias/new
  # GET /uchronias/new.json
  def new
    @uchronia = Uchronia.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @uchronia }
    end
  end

  # GET /uchronias/1/edit
  def edit
    @uchronia = Uchronia.find(params[:id])
  end

  # POST /uchronias
  # POST /uchronias.json
  def create
    @uchronia = Uchronia.new(params[:uchronia])

    respond_to do |format|
      if @uchronia.save
        format.html { redirect_to @uchronia, notice: 'Uchronia was successfully created.' }
        format.json { render json: @uchronia, status: :created, location: @uchronia }
      else
        format.html { render action: "new" }
        format.json { render json: @uchronia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /uchronias/1
  # PUT /uchronias/1.json
  def update
    @uchronia = Uchronia.find(params[:id])

    respond_to do |format|
      if @uchronia.update_attributes(params[:uchronia])
        format.html { redirect_to @uchronia, notice: 'Uchronia was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @uchronia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uchronias/1
  # DELETE /uchronias/1.json
  def destroy
    @uchronia = Uchronia.find(params[:id])
    @uchronia.destroy

    respond_to do |format|
      format.html { redirect_to uchronias_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/uchronia_helper.rb
module UchroniaHelper
end

app/helpers/uchronias_helper.rb
module UchroniasHelper
end

app/views/uchronias/_form.html.erb
<%= form_for(@uchronia) do |f| %>
  <% if @uchronia.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@uchronia.errors.count, "error") %> prohibited this uchronia from being saved:</h2>

      <ul>
      <% @uchronia.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_id %><br />
    <%= f.select :image_id, Image.order("title").collect {|i| [i.title, i.id]}.insert(0, ["-", nil]) %>
  </div>
  <div class="field">
    <%= f.label :media_embed %><br />
    <%= f.text_area :media_embed %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :pod %><br />
    <%= f.text_area :pod %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  
  <div class="field">
    <%= f.label :hidden %><br />
    <%= f.check_box :hidden %>
  </div>
  
  <div class="field">
    <%= f.label :show_bio %><br />
    <%= f.check_box :show_bio %>
  </div>  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/uchronias/_show_public.html.erb
<h1>Uchronie <%= uchronia.title %></h1>

<div class="row">
	
<article class="col-2">
	<% if uchronia.image %>
		<%= image_tag uchronia.image.image.url, options = {:data => { :image_id => uchronia.image.id } } %>
	<% end %> 
	
	<% if uchronia.media_embed %>
		<%= uchronia.media_embed.html_safe %>
	<% end %>
	
	<p>
	  <b>Point of Divergence</b> <%= uchronia.pod %>
	</p>
	
	<p><b>Entwicklung</b> <%= uchronia.description.html_safe %></p>
	
	<p>
		<b>Letzte Aktualisierung</b> <%= uchronia.updated_at.to_datetime.strftime("%d.%m.%Y")  %>
	</p>
	
	<p>
		<b>Uchronisten</b> 
	<% uchronia.uchronists.each do |u| %>
		<%= link_to u.name, "#/" + u.slug %>
	<% end %>
	</p>

</article>

<div class="col-2">
	<aside class="post-it bio_translation <%= "hide-bio" if !uchronia.show_bio %>">
		<b>Ihre Biographie</b>
		<div class="bio_translation_content"></div>
		<%= link_to "Biographie ändern", "#/biographie-transformator", {:class=>"uchronia_link", :rel=>uchronia.slug} %>
	</aside>
</div>

</div>

<div class="row col-1">
	<nav>
		<%= link_to "Weiter zur nächsten Uchronie", "#/" + uchronia.next_uchronia.slug %> oder <%= link_to "zurück zum Start", "#/start" %>
	</nav>
</div>

app/views/uchronias/edit.html.erb
<h1>Editing uchronia</h1>

<%= render 'form' %>

<%= link_to 'Show', @uchronia %> |
<%= link_to 'Back', uchronias_path %>

app/views/uchronias/index.html.erb
<h1>Listing uchronias</h1>

<table class="table">
  <tr>
    <th>Image</th>
    <th>Show Bio</th>
    <th>Media embed</th>
    <th>Title</th>
    <th>Pod</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @uchronias.each do |uchronia| %>
  <tr>
    <td><%= uchronia.image_id %></td>
    <td><%= uchronia.show_bio %></td>    
    <td><%= uchronia.media_embed %></td>
    <td><%= uchronia.title %></td>
    <td><%= uchronia.pod %></td>
    <td><%= uchronia.description %></td>
    <td><%= link_to 'Show', uchronia %></td>
    <td><%= link_to 'Edit', edit_uchronia_path(uchronia) %></td>
    <td><%= link_to 'Destroy', uchronia, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Uchronia', new_uchronia_path %>

app/views/uchronias/new.html.erb
<h1>New uchronia</h1>

<%= render 'form' %>

<%= link_to 'Back', uchronias_path %>

app/views/uchronias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image:</b>
  <%= @uchronia.image_id %>
</p>

<p>
  <b>Media embed:</b>
  <%= @uchronia.media_embed %>
</p>

<p>
  <b>Title:</b>
  <%= @uchronia.title %>
</p>

<p>
  <b>Pod:</b>
  <%= @uchronia.pod %>
</p>

<p>
  <b>Description:</b>
  <%= @uchronia.description %>
</p>


<%= link_to 'Edit', edit_uchronia_path(@uchronia) %> |
<%= link_to 'Back', uchronias_path %>